[env:hallard_rp2040_rfm95]
extends = rp2040_base
board = rpipico
upload_protocol = picotool

# add our variants files to the include and src paths
build_flags = ${rp2040_base.build_flags} 
  -D PRIVATE_HW
  -Ivariants/diy/hallard_rp2040_rfm95
  -DDEBUG_RP2040_PORT=Serial
  -DHW_SPI0_DEVICE
  -L "${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m0plus"
lib_deps =
  ${rp2040_base.lib_deps}
debug_build_flags = ${rp2040_base.build_flags}
debug_tool = cmsis-dap
