; WeMos ESP32s2 Mini + Hallard WeMos LoRa Shield
[env:hallard-wemos-esp32s2]
extends = esp32s2_base
board = lolin_s2_mini
board_level = extra
board_upload.flash_size = 4MB ;Specify the FLASH capacity as 4MB
#board_build.arduino.memory_type = qio_opi ;Enable internal PSRAM
build_unflags =
  ${esp32s2_base.build_unflags}
  -D ARDUINO_USB_MODE=1
build_flags =
  ${esp32s2_base.build_flags}
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D PRIVATE_HW
  -I variants/diy/hallard_wemos_esp32s2
upload_protocol = esptool
upload_port = /dev/ttyACM0
